name: 'newbiefy-test'
on:
  create:
    branches:
      - newbiefy*

jobs:
  newbiefy:
    runs-on: ubuntu-latest
    steps:
      - uses: dansyuqri/newbiefy@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}